# Generated by Django 4.2.3 on 2024-11-10 01:51

from django.db import migrations, models
import django_rest_passwordreset.models


class Migration(migrations.Migration):
    dependencies = [
        ("django_rest_passwordreset", "0004_alter_resetpasswordtoken_user_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="resetpasswordtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=django_rest_passwordreset.models.set_default_expiry,
                verbose_name="When does this token expire",
            ),
        ),
    ]
